trigger:
  branches:
    include:
      - main  # Trigger pipeline for 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

jobs:
- job: Build
  displayName: 'Build the React and Flask App'
  steps:
    - checkout: self  # Checkout the repository

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Install Node.js version 16.x
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install  # Install React dependencies
      displayName: 'Install React dependencies'
      condition: succeeded()  # This ensures the step only runs if the previous step succeeded

    - script: |
        cd client
        npm run build  # Build the React app
      displayName: 'Build React app'
      condition: succeeded()  # Only run if 'Install React dependencies' step succeeded

    - script: |
        mkdir -p app/static  # Ensure static folder exists
        cp -r client/build/* app/static/  # Move build files to Flask static folder
      displayName: 'Move React build to Flask static'
      condition: succeeded()  # Only run if 'Build React app' step succeeded

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'  # Specify the Python version
      displayName: 'Install Python'

    - script: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install -r requirements.txt  # Install Python dependencies
      displayName: 'Install Flask dependencies'

    - script: |
        lftp -u $(FTP_USERNAME),$(FTP_PASSWORD) ftp://ftp.anthonybturner.com -e "
          mirror -R app /home/fmua7eh7xba3/app; 
          mirror -R client/build /home/fmua7eh7xba3/app/static; 
          quit"
      env:
        FTP_USERNAME: $(FTP_USERNAME)
        FTP_PASSWORD: $(FTP_PASSWORD)
      displayName: 'Deploy Flask app to GoDaddy via FTP'
