trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    displayName: 'Checkout repository'

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd client
      npm install
    displayName: 'Install React dependencies'

  - script: |
      cd client
      npm run build
    displayName: 'Build React app'

  - script: |
      mkdir -p app/static
      cp -r client/build/* app/static/
    displayName: 'Move React build to Flask static'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Install Python'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install Flask dependencies'

  - script: |
      lftp -u $(FTP_USERNAME),$(FTP_PASSWORD) $(FTP_HOST) -e "
        mirror -R app /home/fmua7eh7xba3/app; 
        mirror -R client/build /home/fmua7eh7xba3/app/static; 
        quit"
    env:
      FTP_HOST: $(FTP_HOST)
      FTP_USERNAME: $(FTP_USERNAME)
      FTP_PASSWORD: $(FTP_PASSWORD)
    displayName: 'Deploy Flask app to GoDaddy via FTP'
