trigger:
  branches:
    include:
      - main  # Trigger pipeline for 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

jobs:
- job: Build
  displayName: 'Build the React and Flask App'
  steps:
    - checkout: self  # Checkout the repository
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Install Node.js version 16.x
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install  # Install React dependencies
      displayName: 'Install React dependencies'

    - script: |
        cd client
        npm run build  # Build the React app
      displayName: 'Build React app'

    - script: |
        mkdir -p app/static  # Ensure static folder exists
        cp -r client/build/* app/static/  # Move build files to Flask static folder
      displayName: 'Move React build to Flask static'

- job: InstallPython
  displayName: 'Install Python and Flask Dependencies'
  dependsOn: Build  # This job depends on the completion of the Build job
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'  # Install Python version 3.x
      displayName: 'Install Python'

    - script: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install -r requirements.txt  # Install Flask dependencies
      displayName: 'Install Flask dependencies'

- job: Deploy
  displayName: 'Deploy the App to GoDaddy via FTP'
  dependsOn: InstallPython  # This job depends on the completion of the InstallPython job
  steps:
    - script: |
        lftp -u $(FTP_USERNAME),$(FTP_PASSWORD) ftp://ftp.anthonybturner.com -e "
          mirror -R app /home/fmua7eh7xba3/app; 
          mirror -R client/build /home/fmua7eh7xba3/app/static; 
          quit"
      env:
        FTP_USERNAME: $(FTP_USERNAME)
        FTP_PASSWORD: $(FTP_PASSWORD)
      displayName: 'Deploy Flask app to GoDaddy via FTP'
