trigger:
  branches:
    include:
      - main  # Trigger pipeline for 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

jobs:
- job: Build_and_Deploy
  displayName: 'Build and Deploy React and Flask App'
  steps:
  - checkout: self

  # Step 2: Install Node.js and React dependencies
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd client
      npm install
    displayName: 'Install React dependencies'

  # Step 3: Build React app
  - script: |
      cd client
      npm run build
    displayName: 'Build React app'

  # Step 4: Copy React build to Flask static directory
  - script: |
      mkdir -p app/static  # Ensure the static folder exists
      cp -r client/build/* app/static/
    displayName: 'Move React build to Flask static'

  # Step 5: Install Python and Flask dependencies
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Install Python'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install Flask dependencies'

  # Step 6: Deploy Flask app to GoDaddy via FTP
  - script: |
      lftp -u $(FTP_USERNAME),$(FTP_PASSWORD) ftp://ftp.anthonybturner.com -e "
        set ftp:ssl-allow no;  # Disable SSL if needed
        mirror -R app /home/fmua7eh7xba3/app; 
        mirror -R client/build /home/fmua7eh7xba3/app/static; 
        quit"
    env:
      FTP_USERNAME: $(FTP_USERNAME)
      FTP_PASSWORD: $(FTP_PASSWORD)
    displayName: 'Deploy Flask app to GoDaddy via FTP'
