trigger:
  branches:
    include:
      - main  # Trigger pipeline for 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

jobs:
- job: Build
  displayName: 'Build the React and Flask App'
  steps:
    - checkout: self  # Checkout the repository

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Install Node.js version 16.x
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install  # Install React dependencies
      displayName: 'Install React dependencies'
      condition: succeeded()  # This ensures the step only runs if the previous step succeeded

    

    - script: |
        lftp -u $(FTP_USERNAME),$(FTP_PASSWORD) ftp://ftp.anthonybturner.com -e "
          mirror -R app /home/fmua7eh7xba3/app; 
          mirror -R client/build /home/fmua7eh7xba3/app/static; 
          quit"
      env:
        FTP_USERNAME: $(FTP_USERNAME)
        FTP_PASSWORD: $(FTP_PASSWORD)
      displayName: 'Deploy Flask app to GoDaddy via FTP'
